/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    reviews: Review;
    'site-settings': SiteSetting;
    'gold-price': GoldPrice;
    copywriting: Copywriting;
    articles: Article;
    testimonials: Testimonial;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'gold-price': GoldPriceSelect<false> | GoldPriceSelect<true>;
    copywriting: CopywritingSelect<false> | CopywritingSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('id' | 'en' | 'my') | ('id' | 'en' | 'my')[];
  globals: {};
  globalsSelect: {};
  locale: 'id' | 'en' | 'my';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Kelola semua tenant (website) dalam sistem. Hanya Owner yang bisa mengakses menu ini.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * Contoh: Logam Mulia Antam
   */
  name: string;
  /**
   * Contoh: logam-mulia-antam. Tidak boleh ada spasi.
   */
  slug: string;
  isActive?: boolean | null;
  /**
   * Tambahkan semua domain yang dipakai tenant ini (termasuk www dan non-www). Index digunakan untuk query cepat.
   */
  domains: {
    /**
     * Contoh: www.logammulia-antam.com atau localhost:4321
     */
    domain: string;
    id?: string | null;
  }[];
  /**
   * Domain utama untuk canonical URL. Contoh: www.logammulia-antam.com
   */
  primaryDomain?: string | null;
  /**
   * Warna utama brand. Contoh: #D4AF37
   */
  primaryColor?: string | null;
  primaryDarkColor?: string | null;
  secondaryColor?: string | null;
  backgroundDarkColor?: string | null;
  surfaceDarkColor?: string | null;
  /**
   * Default sama dengan primary color
   */
  navbarBgColor?: string | null;
  buttonColor?: string | null;
  /**
   * Warna tombol Add to Cart dan Checkout
   */
  cartButtonColor?: string | null;
  cartTextColor?: string | null;
  productTitleColor?: string | null;
  productPriceColor?: string | null;
  fontFamily?: ('Inter' | 'Poppins' | 'Roboto' | 'Outfit' | 'Plus Jakarta Sans' | 'Nunito') | null;
  /**
   * URL untuk trigger rebuild Vercel saat konten berubah.
   */
  vercelDeployHookUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Owner dapat mengakses semua tenant. Admin hanya bisa akses data tenant-nya.
   */
  roles: ('owner' | 'admin' | 'editor' | 'customer')[];
  /**
   * Tenant yang dimiliki user ini. Owner tidak perlu isi field ini.
   */
  tenant?: (number | null) | Tenant;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Tenant pemilik kategori ini.
   */
  tenant?: (number | null) | Tenant;
  name: string;
  image?: (number | null) | Media;
  /**
   * Urutan tampilan (kecil ke besar)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Tenant pemilik produk ini.
   */
  tenant?: (number | null) | Tenant;
  name: string;
  image: number | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  stock: number;
  price: number;
  strikePrice?: number | null;
  isFeatured?: boolean | null;
  category: number | Category;
  soldCount?: number | null;
  rating?: number | null;
  /**
   * Urutan tampilan (kecil ke besar)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  tenant?: (number | null) | Tenant;
  product: number | Product;
  userName: string;
  rating: number;
  comment: string;
  /**
   * Optional testimonial image
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pengaturan situs per tenant: SEO, kontak, pembayaran, pengiriman.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Tenant yang dimiliki settings ini.
   */
  tenant?: (number | null) | Tenant;
  logo?: (number | null) | Media;
  /**
   * Ikon browser dalam format SVG (Modern).
   */
  faviconSvg?: (number | null) | Media;
  /**
   * Ikon browser dalam format ICO (Kompatibilitas lama).
   */
  faviconIco?: (number | null) | Media;
  /**
   * Nama brand untuk Navbar, Footer, dan Copyright
   */
  brandName: string;
  metaTitle: string;
  metaDescription?: string | null;
  /**
   * Gambar OG untuk social sharing. Ukuran ideal 1200x630px. Jika kosong, akan menggunakan gambar default.
   */
  ogImage?: (number | null) | Media;
  googleSearchConsoleCode?: string | null;
  googleAnalyticsId?: string | null;
  /**
   * Mulai dengan kode negara, contoh: 6281234567890
   */
  whatsappNumber: string;
  email?: string | null;
  address?: string | null;
  /**
   * Teks singkat di bagian footer.
   */
  footerAbout?: string | null;
  shippingMethods?:
    | {
        name: string;
        price: number;
        id?: string | null;
      }[]
    | null;
  paymentChannels?:
    | {
        bankName: string;
        accountName: string;
        accountNumber: string;
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Contoh: https://facebook.com/namapage
   */
  facebook?: string | null;
  /**
   * Contoh: https://instagram.com/namaakun
   */
  instagram?: string | null;
  /**
   * Contoh: https://x.com/namaakun
   */
  twitter?: string | null;
  /**
   * Contoh: https://tiktok.com/@namaakun
   */
  tiktok?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Harga emas live per tenant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gold-price".
 */
export interface GoldPrice {
  id: number;
  tenant?: (number | null) | Tenant;
  currentPrice: number;
  /**
   * Harga asli sebelum diskon untuk tampilan coret.
   */
  strikePrice?: number | null;
  discount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Teks copywriting halaman per tenant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "copywriting".
 */
export interface Copywriting {
  id: number;
  tenant?: (number | null) | Tenant;
  heroTitle: string;
  servicesDescription: string;
  advantagesTitle: string;
  advantages?:
    | {
        icon: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  whyTitle: string;
  whySubtitle: string;
  whyFeatures?:
    | {
        icon: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Pilih dan urutkan produk yang akan tampil di bagian Unggulan di halaman depan.
   */
  featuredProducts?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: string | null;
  publishDate?: string | null;
  viewCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  tenant?: (number | null) | Tenant;
  reviewerName?: string | null;
  /**
   * City or Region (e.g., Jakarta, Makassar)
   */
  location?: string | null;
  avatar?: (number | null) | Media;
  starRating: number;
  reviewText?: string | null;
  /**
   * Photo of the product or testimony
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Transaksi yang dibuat oleh pelanggan saat checkout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  /**
   * Diisi otomatis dari frontend saat checkout.
   */
  tenant?: (number | null) | Tenant;
  /**
   * Generated automatically at checkout
   */
  orderId: string;
  status: 'Pending' | 'Paid' | 'Shipped' | 'Completed' | 'Cancelled';
  customerDetails?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  items?:
    | {
        productId?: string | null;
        productName?: string | null;
        quantity?: number | null;
        priceAtPurchase?: number | null;
        id?: string | null;
      }[]
    | null;
  shippingMethod?: string | null;
  shippingCost?: number | null;
  paymentChannel?: string | null;
  subtotal: number;
  total: number;
  /**
   * URL dari Supabase Storage (diisi otomatis)
   */
  paymentProofUrl?: string | null;
  /**
   * Masukkan Nomor Resi jika pesanan sudah dikirim
   */
  trackingNumber?: string | null;
  supabaseUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'gold-price';
        value: number | GoldPrice;
      } | null)
    | ({
        relationTo: 'copywriting';
        value: number | Copywriting;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isActive?: T;
  domains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  primaryDomain?: T;
  primaryColor?: T;
  primaryDarkColor?: T;
  secondaryColor?: T;
  backgroundDarkColor?: T;
  surfaceDarkColor?: T;
  navbarBgColor?: T;
  buttonColor?: T;
  cartButtonColor?: T;
  cartTextColor?: T;
  productTitleColor?: T;
  productPriceColor?: T;
  fontFamily?: T;
  vercelDeployHookUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  tenant?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  image?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  description?: T;
  stock?: T;
  price?: T;
  strikePrice?: T;
  isFeatured?: T;
  category?: T;
  soldCount?: T;
  rating?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  tenant?: T;
  product?: T;
  userName?: T;
  rating?: T;
  comment?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tenant?: T;
  logo?: T;
  faviconSvg?: T;
  faviconIco?: T;
  brandName?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  googleSearchConsoleCode?: T;
  googleAnalyticsId?: T;
  whatsappNumber?: T;
  email?: T;
  address?: T;
  footerAbout?: T;
  shippingMethods?:
    | T
    | {
        name?: T;
        price?: T;
        id?: T;
      };
  paymentChannels?:
    | T
    | {
        bankName?: T;
        accountName?: T;
        accountNumber?: T;
        logo?: T;
        id?: T;
      };
  facebook?: T;
  instagram?: T;
  twitter?: T;
  tiktok?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gold-price_select".
 */
export interface GoldPriceSelect<T extends boolean = true> {
  tenant?: T;
  currentPrice?: T;
  strikePrice?: T;
  discount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "copywriting_select".
 */
export interface CopywritingSelect<T extends boolean = true> {
  tenant?: T;
  heroTitle?: T;
  servicesDescription?: T;
  advantagesTitle?: T;
  advantages?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  whyTitle?: T;
  whySubtitle?: T;
  whyFeatures?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  featuredProducts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  featuredImage?: T;
  content?: T;
  author?: T;
  publishDate?: T;
  viewCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  tenant?: T;
  reviewerName?: T;
  location?: T;
  avatar?: T;
  starRating?: T;
  reviewText?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  tenant?: T;
  orderId?: T;
  status?: T;
  customerDetails?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        address?: T;
      };
  items?:
    | T
    | {
        productId?: T;
        productName?: T;
        quantity?: T;
        priceAtPurchase?: T;
        id?: T;
      };
  shippingMethod?: T;
  shippingCost?: T;
  paymentChannel?: T;
  subtotal?: T;
  total?: T;
  paymentProofUrl?: T;
  trackingNumber?: T;
  supabaseUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}