/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    reviews: Review;
    'site-settings': SiteSetting;
    'gold-price': GoldPrice;
    copywriting: Copywriting;
    articles: Article;
    testimonials: Testimonial;
    transactions: Transaction;
    'savings-balances': SavingsBalance;
    'savings-ledgers': SavingsLedger;
    customers: Customer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'gold-price': GoldPriceSelect<false> | GoldPriceSelect<true>;
    copywriting: CopywritingSelect<false> | CopywritingSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'savings-balances': SavingsBalancesSelect<false> | SavingsBalancesSelect<true>;
    'savings-ledgers': SavingsLedgersSelect<false> | SavingsLedgersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('id' | 'en' | 'my') | ('id' | 'en' | 'my')[];
  globals: {};
  globalsSelect: {};
  locale: 'id' | 'en' | 'my';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Kelola semua tenant (website) dalam sistem. Hanya Owner yang bisa mengakses menu ini.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  /**
   * Contoh: Logam Mulia Antam
   */
  name: string;
  /**
   * Contoh: logam-mulia-antam. Tidak boleh ada spasi.
   */
  slug: string;
  isActive?: boolean | null;
  /**
   * Tambahkan semua domain yang dipakai tenant ini (termasuk www dan non-www). Index digunakan untuk query cepat.
   */
  domains: {
    /**
     * Contoh: www.logammulia-antam.com atau localhost:4321
     */
    domain: string;
    id?: string | null;
  }[];
  /**
   * Domain utama untuk canonical URL. Contoh: www.logammulia-antam.com
   */
  primaryDomain?: string | null;
  /**
   * Pilih layout utama untuk website ini
   */
  theme_layout?: ('default' | 'luxury' | 'luxury-branded') | null;
  /**
   * Warna utama brand. Contoh: #D4AF37
   */
  primaryColor?: string | null;
  primaryDarkColor?: string | null;
  secondaryColor?: string | null;
  backgroundDarkColor?: string | null;
  surfaceDarkColor?: string | null;
  /**
   * Default sama dengan primary color
   */
  navbarBgColor?: string | null;
  buttonColor?: string | null;
  /**
   * Warna tombol Add to Cart dan Checkout
   */
  cartButtonColor?: string | null;
  /**
   * Kosongkan untuk otomatis menyesuaikan Light/Dark Mode
   */
  cartTextColor?: string | null;
  /**
   * Kosongkan untuk otomatis menyesuaikan Light/Dark Mode
   */
  productTitleColor?: string | null;
  productPriceColor?: string | null;
  fontFamily?: ('Inter' | 'Poppins' | 'Roboto' | 'Outfit' | 'Plus Jakarta Sans' | 'Nunito' | 'Fjalla One') | null;
  /**
   * Warna untuk tombol di modal success & form upload bukti.
   */
  successButtonColor?: string | null;
  /**
   * Upload maksimal 3 gambar untuk slider hero di halaman utama.
   */
  heroSlider?:
    | {
        image: number | Media;
        /**
         * Teks yang akan muncul di atas gambar slider.
         */
        title?: string | null;
        /**
         * Warna teks judul slide. Default: #FFFFFF (Putih).
         */
        textColor?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL untuk trigger rebuild Vercel saat konten berubah.
   */
  vercelDeployHookUrl?: string | null;
  /**
   * URL untuk trigger rebuild Cloudflare Pages saat konten berubah.
   */
  cloudflareDeployHookUrl?: string | null;
  /**
   * Aktifkan fitur Tabungan Emas (Dashboard Simpanan) untuk tenant ini.
   */
  enableGoldSavings?: boolean | null;
  /**
   * Aktifkan fitur Dark Mode di website front-end.
   */
  enableDarkMode?: boolean | null;
  /**
   * Prefix kustom untuk ID Anggota Tabungan Emas (misal: CGM). Jika kosong, akan menggunakan inisial dari Brand Name atau AKUAN.
   */
  savingsMemberIdPrefix?: string | null;
  /**
   * Label kustom untuk nama/simbol emas tabungan (misal: GAP). Jika kosong, akan menggunakan GAP.
   */
  savingsGoldSymbol?: string | null;
  /**
   * Aktifkan tombol "Beli via WA" pada setiap kartu produk di beranda dan halaman produk.
   */
  showWhatsAppBuyButton?: boolean | null;
  /**
   * Jika diaktifkan, tampilan produk di halaman /products untuk perangkat mobile akan menjadi 2 kolom. Default adalah 1 kolom.
   */
  enableTwoColumnGridMobile?: boolean | null;
  /**
   * Jika diaktifkan, akan menampilkan text/pengumuman diatas navbar.
   */
  enableAnnouncement?: boolean | null;
  /**
   * Text yang akan ditampilkan di baris pengumuman. Contoh: Gratis Ongkir Seluruh Indonesia
   */
  announcementText?: string | null;
  /**
   * Link tujuan saat text pengumuman diklik. Contoh: /products atau link eksternal.
   */
  announcementLink?: string | null;
  /**
   * Jika dinonaktifkan, ulasan pelanggan (bintang, total ulasan, list review) di halaman detail produk akan disembunyikan. Default aktif.
   */
  enableCustomerReviews?: boolean | null;
  /**
   * Judul halaman panduan tabungan emas.
   */
  guideTitle?: string | null;
  /**
   * Tulis panduan tabungan emas menggunakan rich text editor.
   */
  guideContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Owner dapat mengakses semua tenant. Admin hanya bisa akses data tenant-nya.
   */
  roles: ('owner' | 'admin' | 'editor' | 'customer')[];
  /**
   * Tenant yang dimiliki user ini. Owner tidak perlu isi field ini.
   */
  tenant?: (number | null) | Tenant;
  /**
   * Data Know Your Customer untuk fitur tabungan emas.
   */
  kyc?: {
    kycType?: ('IC' | 'Passport') | null;
    kycNumber?: string | null;
    bankName?: string | null;
    bankAccountNumber?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Tenant pemilik kategori ini.
   */
  tenant?: (number | null) | Tenant;
  name: string;
  /**
   * Pilih kategori induk jika ini adalah sub-kategori.
   */
  parent?: (number | null) | Category;
  image?: (number | null) | Media;
  /**
   * Aktifkan untuk menampilkan kategori ini di Homepage (Maksimal 3 kategori akan ditampilkan).
   */
  showOnHomepage?: boolean | null;
  /**
   * Jika diaktifkan, kategori tidak akan muncul di Navbar. (Hanya berlaku untuk Kategori Utama. Sub-kategori tetap tampil jika parent-nya tampil)
   */
  hideFromNavbar?: boolean | null;
  /**
   * Urutan tampilan (kecil ke besar)
   */
  sortOrder?: number | null;
  /**
   * Jika diisi, klik pada kategori ini akan mengarah ke URL ini (contoh: /products). Path akan otomatis disesuaikan dengan bahasa (contoh: /en/products).
   */
  customUrl?: string | null;
  /**
   * Jika diaktifkan, kategori ini tidak akan muncul sebagai filter di halaman /products.
   */
  hideFromProductsPage?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Tenant pemilik produk ini.
   */
  tenant?: (number | null) | Tenant;
  name: string;
  image: number | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Masukkan pilihan warna untuk produk ini. Khusus untuk tema Luxury (Branded Goods).
   */
  colors?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  stock: number;
  price: number;
  /**
   * Persentase diskon. Jika diisi bersama Spread Price, Harga Akhir = (Harga Dasar * (1 - Diskon/100)) - Spread Price. (Khusus Luxury Branded Goods)
   */
  discountPercent?: number | null;
  /**
   * Potongan/penambahan nilai tetap setelah diskon dihitung. (Khusus Luxury Branded Goods)
   */
  spreadPrice?: number | null;
  strikePrice?: number | null;
  isFeatured?: boolean | null;
  /**
   * Jika diaktifkan, produk ini akan muncul di Homepage. Jika tidak, hanya di halaman Products. (Khusus Luxury Branded Goods)
   */
  showOnHomepage?: boolean | null;
  category: number | Category;
  soldCount?: number | null;
  rating?: number | null;
  /**
   * Urutan tampilan (kecil ke besar)
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  tenant?: (number | null) | Tenant;
  product: number | Product;
  userName: string;
  rating: number;
  comment: string;
  /**
   * Optional testimonial image
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pengaturan situs per tenant: SEO, kontak, pembayaran, pengiriman.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Tenant yang dimiliki settings ini.
   */
  tenant?: (number | null) | Tenant;
  logo?: (number | null) | Media;
  /**
   * Ikon browser dalam format SVG (Modern).
   */
  faviconSvg?: (number | null) | Media;
  /**
   * Ikon browser dalam format ICO (Kompatibilitas lama).
   */
  faviconIco?: (number | null) | Media;
  /**
   * Nama brand untuk Navbar, Footer, dan Copyright
   */
  brandName: string;
  metaTitle: string;
  metaDescription?: string | null;
  /**
   * Gambar OG untuk social sharing. Ukuran ideal 1200x630px. Jika kosong, akan menggunakan gambar default.
   */
  ogImage?: (number | null) | Media;
  googleSearchConsoleCode?: string | null;
  googleAnalyticsId?: string | null;
  /**
   * Mulai dengan kode negara, contoh: 6281234567890
   */
  whatsappNumber: string;
  enableFloatingWA?: boolean | null;
  /**
   * Pesan ini akan ditambahkan setelah "Halo Admin {Brand Name}, "
   */
  whatsappDefaultMessage?: string | null;
  email?: string | null;
  address?: string | null;
  /**
   * Teks singkat di bagian footer.
   */
  footerAbout?: string | null;
  /**
   * Teks bebas yang ditampilkan di bagian bawah footer. Jika dikosongkan, otomatis menggunakan format: "© {tahun} {Brand Name}. All rights reserved."
   */
  footerCopyright?: string | null;
  /**
   * Mengatur perataan teks copyright khusus pada tampilan mobile (layar kecil).
   */
  copyrightMobileAlign?: ('left' | 'center' | 'right') | null;
  shippingMethods?:
    | {
        name: string;
        price: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Tentukan di mana form upload bukti pembayaran akan ditampilkan.
   */
  enableTopupProofUpload: 'checkout' | 'savings' | 'both' | 'none';
  paymentChannels?:
    | {
        /**
         * Tentukan di mana channel pembayaran ini akan ditampilkan.
         */
        displayLocation: 'checkout' | 'savings' | 'both';
        bankName: string;
        accountName?: string | null;
        accountNumber?: string | null;
        phoneNumber?: string | null;
        logo?: (number | null) | Media;
        /**
         * Gambar QRIS / QR Code pembayaran. Digunakan pada halaman upload bukti transaksi di checkout.
         */
        qrCode?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Contoh: https://facebook.com/namapage
   */
  facebook?: string | null;
  /**
   * Contoh: https://instagram.com/namaakun
   */
  instagram?: string | null;
  enableFloatingInstagram?: boolean | null;
  /**
   * Contoh: https://x.com/namaakun
   */
  twitter?: string | null;
  /**
   * Contoh: https://tiktok.com/@namaakun
   */
  tiktok?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Harga emas live per tenant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gold-price".
 */
export interface GoldPrice {
  id: number;
  tenant?: (number | null) | Tenant;
  currentPrice: number;
  /**
   * Persentase spread potongan untuk harga jual semula (buyback). Default adalah 4 (4%).
   */
  buybackSpread?: number | null;
  /**
   * Harga asli sebelum diskon untuk tampilan coret.
   */
  strikePrice?: number | null;
  discount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Teks copywriting halaman per tenant.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "copywriting".
 */
export interface Copywriting {
  id: number;
  tenant?: (number | null) | Tenant;
  heroTitle: string;
  servicesDescription: string;
  advantagesTitle: string;
  advantages?:
    | {
        icon: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  whyTitle: string;
  whySubtitle: string;
  whyFeatures?:
    | {
        icon: string;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Pilih dan urutkan produk yang akan tampil di bagian Unggulan di halaman depan.
   */
  featuredProducts?: (number | Product)[] | null;
  /**
   * Gambar statis ini akan menjadi background dengan efek parallax di homepage untuk tema Luxury Branded Goods.
   */
  luxuryParallaxImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  featuredImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: string | null;
  publishDate?: string | null;
  viewCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  tenant?: (number | null) | Tenant;
  /**
   * Pilih tampilan testimoni di halaman website.
   */
  type: 'text' | 'image_only';
  reviewerName?: string | null;
  /**
   * City or Region (e.g., Jakarta, Makassar)
   */
  location?: string | null;
  avatar?: (number | null) | Media;
  starRating?: number | null;
  reviewText?: string | null;
  /**
   * Photo of the product (Opsi 1) OR WhatsApp Screenshot (Opsi 2)
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Transaksi yang dibuat oleh pelanggan saat checkout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  /**
   * Diisi otomatis dari frontend saat checkout.
   */
  tenant?: (number | null) | Tenant;
  /**
   * Generated automatically at checkout
   */
  orderId: string;
  status: 'Pending' | 'Paid' | 'Shipped' | 'Completed' | 'Cancelled';
  customerDetails?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  items?:
    | {
        productId?: string | null;
        productName?: string | null;
        quantity?: number | null;
        priceAtPurchase?: number | null;
        id?: string | null;
      }[]
    | null;
  shippingMethod?: string | null;
  shippingCost?: number | null;
  paymentChannel?: string | null;
  subtotal: number;
  total: number;
  /**
   * URL dari Supabase Storage (diisi otomatis)
   */
  paymentProofUrl?: string | null;
  /**
   * Masukkan Nomor Resi jika pesanan sudah dikirim
   */
  trackingNumber?: string | null;
  supabaseUserId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "savings-balances".
 */
export interface SavingsBalance {
  id: number;
  tenant: number | Tenant;
  /**
   * ID pengguna dari sistem otentikasi Supabase.
   */
  supabaseUserId: string;
  customerName?: string | null;
  customerEmail?: string | null;
  balanceGrams: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "savings-ledgers".
 */
export interface SavingsLedger {
  id: number;
  tenant: number | Tenant;
  /**
   * ID pengguna dari sistem otentikasi Supabase.
   */
  supabaseUserId: string;
  customerName?: string | null;
  customerEmail?: string | null;
  transactionType: 'top_up' | 'buy' | 'sell' | 'withdraw_physical' | 'withdraw_fiat';
  /**
   * Bisa berupa Gram atau Fiat tergantung tipe transaksi.
   */
  amount: number;
  /**
   * Mencatat harga emas saat transaksi dilakukan.
   */
  priceSnapshot?: number | null;
  status: 'pending' | 'approved' | 'rejected';
  /**
   * Foto bukti transfer pembayaran untuk transaksi Top Up.
   */
  paymentProof?: (number | null) | Media;
  shippingAddress?: string | null;
  shippingMethod?: string | null;
  bankName?: string | null;
  accountNumber?: string | null;
  accountName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  /**
   * Alamat email customer.
   */
  email: string;
  /**
   * Nama lengkap customer.
   */
  fullName?: string | null;
  /**
   * Tenant tempat customer terdaftar.
   */
  tenant: number | Tenant;
  /**
   * ID pengguna dari sistem otentikasi Supabase.
   */
  supabaseUserId?: string | null;
  /**
   * Ceklis untuk memblokir customer ini agar tidak bisa login ke website.
   */
  isBlocked?: boolean | null;
  /**
   * Data Know Your Customer untuk fitur tabungan emas.
   */
  kyc?: {
    kycType?: ('IC' | 'Passport') | null;
    kycNumber?: string | null;
    bankName?: string | null;
    bankAccountNumber?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'site-settings';
        value: number | SiteSetting;
      } | null)
    | ({
        relationTo: 'gold-price';
        value: number | GoldPrice;
      } | null)
    | ({
        relationTo: 'copywriting';
        value: number | Copywriting;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'savings-balances';
        value: number | SavingsBalance;
      } | null)
    | ({
        relationTo: 'savings-ledgers';
        value: number | SavingsLedger;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isActive?: T;
  domains?:
    | T
    | {
        domain?: T;
        id?: T;
      };
  primaryDomain?: T;
  theme_layout?: T;
  primaryColor?: T;
  primaryDarkColor?: T;
  secondaryColor?: T;
  backgroundDarkColor?: T;
  surfaceDarkColor?: T;
  navbarBgColor?: T;
  buttonColor?: T;
  cartButtonColor?: T;
  cartTextColor?: T;
  productTitleColor?: T;
  productPriceColor?: T;
  fontFamily?: T;
  successButtonColor?: T;
  heroSlider?:
    | T
    | {
        image?: T;
        title?: T;
        textColor?: T;
        id?: T;
      };
  vercelDeployHookUrl?: T;
  cloudflareDeployHookUrl?: T;
  enableGoldSavings?: T;
  enableDarkMode?: T;
  savingsMemberIdPrefix?: T;
  savingsGoldSymbol?: T;
  showWhatsAppBuyButton?: T;
  enableTwoColumnGridMobile?: T;
  enableAnnouncement?: T;
  announcementText?: T;
  announcementLink?: T;
  enableCustomerReviews?: T;
  guideTitle?: T;
  guideContent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  tenant?: T;
  kyc?:
    | T
    | {
        kycType?: T;
        kycNumber?: T;
        bankName?: T;
        bankAccountNumber?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  parent?: T;
  image?: T;
  showOnHomepage?: T;
  hideFromNavbar?: T;
  sortOrder?: T;
  customUrl?: T;
  hideFromProductsPage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  colors?:
    | T
    | {
        name?: T;
        id?: T;
      };
  description?: T;
  stock?: T;
  price?: T;
  discountPercent?: T;
  spreadPrice?: T;
  strikePrice?: T;
  isFeatured?: T;
  showOnHomepage?: T;
  category?: T;
  soldCount?: T;
  rating?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  tenant?: T;
  product?: T;
  userName?: T;
  rating?: T;
  comment?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  tenant?: T;
  logo?: T;
  faviconSvg?: T;
  faviconIco?: T;
  brandName?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  googleSearchConsoleCode?: T;
  googleAnalyticsId?: T;
  whatsappNumber?: T;
  enableFloatingWA?: T;
  whatsappDefaultMessage?: T;
  email?: T;
  address?: T;
  footerAbout?: T;
  footerCopyright?: T;
  copyrightMobileAlign?: T;
  shippingMethods?:
    | T
    | {
        name?: T;
        price?: T;
        id?: T;
      };
  enableTopupProofUpload?: T;
  paymentChannels?:
    | T
    | {
        displayLocation?: T;
        bankName?: T;
        accountName?: T;
        accountNumber?: T;
        phoneNumber?: T;
        logo?: T;
        qrCode?: T;
        id?: T;
      };
  facebook?: T;
  instagram?: T;
  enableFloatingInstagram?: T;
  twitter?: T;
  tiktok?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gold-price_select".
 */
export interface GoldPriceSelect<T extends boolean = true> {
  tenant?: T;
  currentPrice?: T;
  buybackSpread?: T;
  strikePrice?: T;
  discount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "copywriting_select".
 */
export interface CopywritingSelect<T extends boolean = true> {
  tenant?: T;
  heroTitle?: T;
  servicesDescription?: T;
  advantagesTitle?: T;
  advantages?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  whyTitle?: T;
  whySubtitle?: T;
  whyFeatures?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  featuredProducts?: T;
  luxuryParallaxImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  featuredImage?: T;
  content?: T;
  author?: T;
  publishDate?: T;
  viewCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  tenant?: T;
  type?: T;
  reviewerName?: T;
  location?: T;
  avatar?: T;
  starRating?: T;
  reviewText?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  tenant?: T;
  orderId?: T;
  status?: T;
  customerDetails?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        address?: T;
      };
  items?:
    | T
    | {
        productId?: T;
        productName?: T;
        quantity?: T;
        priceAtPurchase?: T;
        id?: T;
      };
  shippingMethod?: T;
  shippingCost?: T;
  paymentChannel?: T;
  subtotal?: T;
  total?: T;
  paymentProofUrl?: T;
  trackingNumber?: T;
  supabaseUserId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "savings-balances_select".
 */
export interface SavingsBalancesSelect<T extends boolean = true> {
  tenant?: T;
  supabaseUserId?: T;
  customerName?: T;
  customerEmail?: T;
  balanceGrams?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "savings-ledgers_select".
 */
export interface SavingsLedgersSelect<T extends boolean = true> {
  tenant?: T;
  supabaseUserId?: T;
  customerName?: T;
  customerEmail?: T;
  transactionType?: T;
  amount?: T;
  priceSnapshot?: T;
  status?: T;
  paymentProof?: T;
  shippingAddress?: T;
  shippingMethod?: T;
  bankName?: T;
  accountNumber?: T;
  accountName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  email?: T;
  fullName?: T;
  tenant?: T;
  supabaseUserId?: T;
  isBlocked?: T;
  kyc?:
    | T
    | {
        kycType?: T;
        kycNumber?: T;
        bankName?: T;
        bankAccountNumber?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}